[versions]

# Gradle
agp = "8.3.2"

# Kotlin Gradle Plugin
kotlinGradlePlugin = "1.8.0"

# Dagger Hilt
hilt = "2.51"
hiltAndroidCompiler = "2.51"

# Navigation
nav = "2.8.4"

# Material
materialVersion = "1.12.0"

# AndroidX
coreKtxVersion = "1.15.0"
appcompatVersion = "1.7.0"
fragmentKtx = "1.8.5"
constraintlayoutVersion = "2.2.0"

# Networking
ktor = "2.3.12"
kotlinxSerialization = "1.6.3"

# Lifecycle
lifecycleExtensions = "2.2.0"
lifecycleRuntimeKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"

# Coroutines
kotlinxCoroutinesCore = "1.7.3"

# Glide
glide = "4.12.0"
glideCompiler = "4.12.0"

# Palette
paletteKtx = "1.0.0"

# Paging3
pagingRuntimeKtx = "3.3.4"

# Timber
timber = "5.0.1"
turbine = "1.0.0"

# Android Testing
espresso = "3.6.1"
androidTestRunner = "1.6.2"
androidTestRules = "1.6.1"
androidTestExt = "1.2.1"
pagingTesting = "3.2.1"
junit = "4.13.2"
coreTesting = "2.2.0"
mockitoCore = "5.3.1"
mockitoKotlin = "5.1.0"

[libraries]

# Android
android-application = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

# Kotlin Gradle Plugin
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinGradlePlugin" }

# Dagger Hilt Plugin
dagger-hilt-android-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

# Navigation SafeArgs
androidx-navigation-safeargs = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "nav" }

# Material
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }

# Navigation
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "nav" }

# Networking
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Lifecycle
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

# Coroutines Dependencies
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }

# Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }

# Palette
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }

# Paging3
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }

# Dagger Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }

# Timber
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Android Testing
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidTestRunner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidTestRules" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidTestExt" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentKtx" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-paging-testing = { module = "androidx.paging:paging-testing", version.ref = "pagingTesting" }